<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alexandra Blasetti Kuhn">
<meta name="dcterms.date" content="2023-10-07">

<title>Capstone Project: NBA Denver Nuggets Shots</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Google_DA_Capstone_Project_files/libs/clipboard/clipboard.min.js"></script>
<script src="Google_DA_Capstone_Project_files/libs/quarto-html/quarto.js"></script>
<script src="Google_DA_Capstone_Project_files/libs/quarto-html/popper.min.js"></script>
<script src="Google_DA_Capstone_Project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Google_DA_Capstone_Project_files/libs/quarto-html/anchor.min.js"></script>
<link href="Google_DA_Capstone_Project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Google_DA_Capstone_Project_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Google_DA_Capstone_Project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Google_DA_Capstone_Project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Google_DA_Capstone_Project_files/libs/bootstrap/bootstrap-a1ff8711b79ae3724c050874b28d9907.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#ask-phase" id="toc-ask-phase" class="nav-link active" data-scroll-target="#ask-phase"><span class="header-section-number">1</span> Ask Phase</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">1.1</span> Introduction</a></li>
  <li><a href="#problem" id="toc-problem" class="nav-link" data-scroll-target="#problem"><span class="header-section-number">1.2</span> Problem</a></li>
  <li><a href="#business-task" id="toc-business-task" class="nav-link" data-scroll-target="#business-task"><span class="header-section-number">1.3</span> Business Task</a></li>
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis"><span class="header-section-number">1.4</span> Hypothesis</a></li>
  </ul></li>
  <li><a href="#prepare-phase" id="toc-prepare-phase" class="nav-link" data-scroll-target="#prepare-phase"><span class="header-section-number">2</span> Prepare Phase</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources"><span class="header-section-number">2.1</span> Data Sources</a></li>
  <li><a href="#variables-and-objects" id="toc-variables-and-objects" class="nav-link" data-scroll-target="#variables-and-objects"><span class="header-section-number">2.2</span> Variables and objects</a></li>
  </ul></li>
  <li><a href="#process-phase" id="toc-process-phase" class="nav-link" data-scroll-target="#process-phase"><span class="header-section-number">3</span> Process Phase</a>
  <ul class="collapse">
  <li><a href="#data-integrity-and-cleaning" id="toc-data-integrity-and-cleaning" class="nav-link" data-scroll-target="#data-integrity-and-cleaning"><span class="header-section-number">3.1</span> Data integrity and cleaning</a></li>
  </ul></li>
  <li><a href="#analyze-phase" id="toc-analyze-phase" class="nav-link" data-scroll-target="#analyze-phase"><span class="header-section-number">4</span> Analyze Phase</a>
  <ul class="collapse">
  <li><a href="#hypothesis-testing-spearmans-rank-correlation-analysis" id="toc-hypothesis-testing-spearmans-rank-correlation-analysis" class="nav-link" data-scroll-target="#hypothesis-testing-spearmans-rank-correlation-analysis"><span class="header-section-number">4.1</span> Hypothesis testing: Spearman’s Rank Correlation Analysis</a></li>
  </ul></li>
  <li><a href="#share-phase" id="toc-share-phase" class="nav-link" data-scroll-target="#share-phase"><span class="header-section-number">5</span> Share Phase</a>
  <ul class="collapse">
  <li><a href="#interactive-dashboard-distance-shot-and-efficiency-rate-by-year-2015-2023" id="toc-interactive-dashboard-distance-shot-and-efficiency-rate-by-year-2015-2023" class="nav-link" data-scroll-target="#interactive-dashboard-distance-shot-and-efficiency-rate-by-year-2015-2023"><span class="header-section-number">5.1</span> Interactive Dashboard: Distance shot and efficiency rate by year (2015-2023)</a></li>
  <li><a href="#distribution-of-distance-shot-by-efficiency-rate" id="toc-distribution-of-distance-shot-by-efficiency-rate" class="nav-link" data-scroll-target="#distribution-of-distance-shot-by-efficiency-rate"><span class="header-section-number">5.2</span> Distribution of Distance Shot by Efficiency Rate</a></li>
  <li><a href="#distribution-of-minutes-left-by-efficiency-rate" id="toc-distribution-of-minutes-left-by-efficiency-rate" class="nav-link" data-scroll-target="#distribution-of-minutes-left-by-efficiency-rate"><span class="header-section-number">5.3</span> Distribution of Minutes Left by Efficiency Rate</a></li>
  <li><a href="#distribution-of-seconds-left-by-efficiency-rate" id="toc-distribution-of-seconds-left-by-efficiency-rate" class="nav-link" data-scroll-target="#distribution-of-seconds-left-by-efficiency-rate"><span class="header-section-number">5.4</span> Distribution of Seconds Left by Efficiency Rate</a></li>
  </ul></li>
  <li><a href="#act-phase" id="toc-act-phase" class="nav-link" data-scroll-target="#act-phase"><span class="header-section-number">6</span> Act Phase</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">6.1</span> Summary</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Capstone Project: NBA Denver Nuggets Shots</h1>
<p class="subtitle lead"><a href="https://coursera.org/share/9b09d281753536153f78a4c58a82e33a">Google Data Analytics Professional Certificate</a></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Alexandra Blasetti Kuhn </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 7, 2023</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">January 17, 2025</p>
    </div>
  </div>
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    An analysis of Denver Nuggets shot data. Highlight: What’s all the controversy about long-distance shots trend in NBA? This project was developed in Quarto (Report) and Shiny (<a href="https://ablasettikuhn.shinyapps.io/dashboard-app/">Interactive Dashboard</a>) using R programming language, and following the 6 data analysis phases from Google Data Analytics Professional Certificate: Ask, Prepare, Process, Analyze, Share, and Act.
  </div>
</div>


</header>


<section id="ask-phase" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Ask Phase</h1>
<hr style="border: 1px solid black;">
<section id="introduction" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1.1</span> Introduction</h2>
<p>The coach of the team wants to understand the effect of some time and location conditionals on the shot conversion from 2015 to 2023. Specifically, He wants to understand what’s the relationship between the time/location of the shot and the shot conversion from 2015 to 2023.</p>
</section>
<section id="problem" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="problem"><span class="header-section-number">1.2</span> Problem</h2>
<p>What’s the relationship between minutes left, seconds left, distance shot and the shot conversion (efficiency rate)? The period of time analyzed was from 2015 to 2023. For domain-specific problems, it is recommended to consult professionals with experience in the field.</p>
</section>
<section id="business-task" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="business-task"><span class="header-section-number">1.3</span> Business Task</h2>
<p>Business task: identify if minutes left, seconds left and distance shot are related to the shot conversion (efficiency rate) throughout the years 2015-2023. Visualize the results in an interactive dashboard.</p>
</section>
<section id="hypothesis" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="hypothesis"><span class="header-section-number">1.4</span> Hypothesis</h2>
<p>Hypothesis: IF the minutes left, seconds left and distance shot* have an effect on shot conversion, THEN there is a relationship between these conditionals and the efficiency rate. This is the alternative hypothesis (H1), while the null hypothesis (H0) states that there is no relationship between the variables. *these conditionals in the main hypothesis will be evaluated as H1, H2 and H3.</p>
<p><br>
</p>
</section>
</section>
<section id="prepare-phase" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Prepare Phase</h1>
<hr style="border: 1px solid black;">
<section id="data-sources" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="data-sources"><span class="header-section-number">2.1</span> Data Sources</h2>
<p>The data is provided directly from https://www.nba.com/stats. It is public and accessible in the R package “ISAR”, data in nba_nuggets_shots.</p>
<p>The data set contains seven seasons of Denver Nuggets shot data from 2015 to 2023. It follows the ROCCC premises (the data is from a reliable organization, original, comprehensive, current, and cited)</p>
<p>Source: http://asbcllc.com/nbastatR/reference/teams_shots.html Credits and owner: nba_nuggets_shots, ISAR package, NBA.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
</section>
<section id="variables-and-objects" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="variables-and-objects"><span class="header-section-number">2.2</span> Variables and objects</h2>
<p>Lets have a <code>glimpse(nba_nuggets_shots)</code> of the dataset. Other options are <code>str()</code> and <code>View()</code></p>
<p>The data set has 62,196 rows and 27 columns. It follows the ROCCC premises and is tidy, organized in long format. We are interested in the following variables: <code>yearSeason</code>, <code>minutesRemaining</code>, <code>secondsRemaining</code>, <code>distanceShot</code>, <code>isShotAttempted</code> and <code>isShotMade</code>. We are going to calculate the Efficiency Rate as <code>isShotMade/isShotAttempted</code> and store the result as the variable <code>EffRate</code> without adding it to the original database.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>EffRate <span class="ot">&lt;-</span> nba_nuggets_shots<span class="sc">$</span>isShotMade<span class="sc">/</span>nba_nuggets_shots<span class="sc">$</span>isShotAttempted</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The main coach and the data analyst agreed that the selected variables are appropriate for exploring the desired relationship, if there is any.</p>
<p><br>
</p>
</section>
</section>
<section id="process-phase" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Process Phase</h1>
<hr style="border: 1px solid black;">
<section id="data-integrity-and-cleaning" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="data-integrity-and-cleaning"><span class="header-section-number">3.1</span> Data integrity and cleaning</h2>
<p>Now we are going to check the NA’s values on the database. We are only using 5 variables so we will <code>select()</code> them first and check for NA’s after.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>na_check <span class="ot">&lt;-</span> nba_nuggets_shots <span class="sc">%&gt;%</span> <span class="fu">select</span>(yearSeason, minutesRemaining, secondsRemaining, distanceShot, isShotAttempted, isShotMade) <span class="sc">%&gt;%</span> <span class="fu">is.na</span>() <span class="sc">%&gt;%</span> <span class="fu">any</span>()</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ifelse</span>(na_check<span class="sc">==</span><span class="cn">TRUE</span>, <span class="st">"There are NA values in the selected columns."</span>, <span class="st">"There are no NA values in the selected columns."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "There are no NA values in the selected columns."</code></pre>
</div>
</div>
<p>Before starting any analysis, let’s explore the objects inside the variables we want to consider. We can use the <code>unique()</code> function on each variable or the <code>distinct()</code> function and the %&gt;%</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>nba_nuggets_shots <span class="sc">%&gt;%</span> <span class="fu">distinct</span>(yearSeason)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(nba_nuggets_shots<span class="sc">$</span>yearSeason)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(nba_nuggets_shots<span class="sc">$</span>minutesRemaining)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(nba_nuggets_shots<span class="sc">$</span>secondsRemaining)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(nba_nuggets_shots<span class="sc">$</span>distanceShot)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(nba_nuggets_shots<span class="sc">$</span>isShotAttempted)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(nba_nuggets_shots<span class="sc">$</span>isShotMade)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To pull out a brief summary of the variables we want to analyze, <code>summary()</code> or <code>skim()</code> functions are both good options. With the skim function we have a visual idea of the data distribution. The Visualizations were also examined with hist() function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>nba_nuggets_shots <span class="sc">%&gt;%</span> <span class="fu">select</span>(yearSeason, minutesRemaining, secondsRemaining, distanceShot, isShotAttempted, isShotMade) <span class="sc">%&gt;%</span> <span class="fu">skim</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">62196</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">logical</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: logical</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 23%">
<col style="width: 14%">
<col style="width: 20%">
<col style="width: 7%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: left;">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">isShotAttempted</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">TRU: 62196</td>
</tr>
<tr class="even">
<td style="text-align: left;">isShotMade</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: left;">FAL: 33009, TRU: 29187</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">yearSeason</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2018.94</td>
<td style="text-align: right;">2.60</td>
<td style="text-align: right;">2015</td>
<td style="text-align: right;">2017</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">2021</td>
<td style="text-align: right;">2023</td>
<td style="text-align: left;">▇▇▅▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">minutesRemaining</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.34</td>
<td style="text-align: right;">3.46</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">▇▅▇▅▅</td>
</tr>
<tr class="odd">
<td style="text-align: left;">secondsRemaining</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">28.78</td>
<td style="text-align: right;">17.46</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">59</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">distanceShot</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12.76</td>
<td style="text-align: right;">10.47</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">84</td>
<td style="text-align: left;">▇▆▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><em>After reviewing and testing the data, we can conclude the data is tidy, organized in long format and there are no NA’s. The EDA-Exploratory data analysis shows that the data does not follow a normal distribution.</em></p>
<p><br>
</p>
</section>
</section>
<section id="analyze-phase" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Analyze Phase</h1>
<hr style="border: 1px solid black;">
<section id="hypothesis-testing-spearmans-rank-correlation-analysis" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="hypothesis-testing-spearmans-rank-correlation-analysis"><span class="header-section-number">4.1</span> Hypothesis testing: Spearman’s Rank Correlation Analysis</h2>
<p>Considering that the data is NOT normally distributed, H1, H2 and H3 are tested with the Spearman’s Rank Correlation Coefficient.</p>
<p><strong>H1: IF the minutes left have an effect on shot conversion, THEN there is a relationship between minutes remaining and the efficiency rate. H0: There is no relationship between the variables.</strong></p>
<p>We are going to perform the correlation test between minutes remaining and efficiency rate and store the results as H1:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>H1 <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(nba_nuggets_shots<span class="sc">$</span>minutesRemaining, EffRate, <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(nba_nuggets_shots$minutesRemaining, EffRate, :
Cannot compute exact p-value with ties</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>H1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  nba_nuggets_shots$minutesRemaining and EffRate
S = 3.9314e+13, p-value = 1.03e-06
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
0.01958973 </code></pre>
</div>
</div>
<p><strong>Conclusion H1/H0</strong></p>
<p>Based on the Spearman’s rank correlation analysis, there is a statistically significant correlation between the variables <code>minutesRemaining</code> and <code>EffRate</code> (rho = 0.0196, p &lt; 0.001). The positive correlation coefficient (rho) suggests a weak positive monotonic relationship between the remaining minutes in a basketball game and the efficiency rate. (warning: correlation does not mean causation).</p>
<p>The large test statistic S provides strong evidence against the null hypothesis H0 (S = 3.9314e+13). This means that the observed correlation is unlikely to be due to random chance. We reject H0 and accept H1.</p>
<p><em>In practice, the analysis suggests that the greater the number of remaining minutes in a basketball game, there is a tendency for the efficiency rate to also increase, although the relationship is weak. This information can be valuable for basketball teams and coaches in understanding the dynamics of the game and making strategic decisions based on the remaining time and efficiency rate.</em></p>
<p><br>
</p>
<p><strong>H2: IF the seconds left have an effect on shot conversion, THEN there is a relationship between seconds remaining and the efficiency rate. H0: There is no relationship between the variables.</strong></p>
<p>We are going to perform the correlation test between seconds remaining and efficiency rate and store the results as H2:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>H2 <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(nba_nuggets_shots<span class="sc">$</span>secondsRemaining, EffRate, <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(nba_nuggets_shots$secondsRemaining, EffRate, :
Cannot compute exact p-value with ties</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>H2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  nba_nuggets_shots$secondsRemaining and EffRate
S = 3.9396e+13, p-value = 1.21e-05
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
0.01754498 </code></pre>
</div>
</div>
<p><strong>Conclusion H2/H0</strong></p>
<p>Based on the Spearman’s rank correlation analysis, there is a statistically significant correlation between the variables <code>secondsRemaining</code> and <code>EffRate</code> (rho = 0.0175, p &lt; 0.001). The positive correlation coefficient (rho) suggests a weak positive monotonic relationship between the remaining seconds in a basketball game and the efficiency rate. (warning: correlation does not mean causation).</p>
<p>The large test statistic S provides strong evidence against the null hypothesis H0 (S = 3.9396e+13). This means that the observed correlation is unlikely to be due to random chance. We reject H0 and accept H2.</p>
<p><em>In practice, the analysis suggests that the greater the number of remaining seconds in a basketball game, there is a tendency for the efficiency rate to also increase, although the relationship is weak. This information can be valuable for basketball teams and coaches in understanding the dynamics of the game and making strategic decisions based on the remaining time and efficiency rate.</em></p>
<p><br>
</p>
<p><strong>H3: IF the distance shot has an effect on shot conversion, THEN there is a relationship between the distance shot and the efficiency rate. H0: There is no relationship between the variables.</strong></p>
<p>We are going to perform the correlation test between distance shot and efficiency rate and store the results as H3:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>H3 <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(nba_nuggets_shots<span class="sc">$</span>distanceShot, EffRate, <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(nba_nuggets_shots$distanceShot, EffRate, method =
"spearman"): Cannot compute exact p-value with ties</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>H3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  nba_nuggets_shots$distanceShot and EffRate
S = 4.989e+13, p-value &lt; 2.2e-16
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
-0.244173 </code></pre>
</div>
</div>
<p><strong>Conclusion H3/H0</strong></p>
<p>Based on the Spearman’s rank correlation analysis, there is a statistically significant correlation between the variables <code>distanceShot</code> and <code>EffRate</code> (rho = -0.2441, p &lt; 0.001). The positive correlation coefficient (rho) suggests a weak negative monotonic relationship between the distance shot in a basketball game and the efficiency rate. (warning: correlation does not mean causation).</p>
<p>The large test statistic S provides strong evidence against the null hypothesis H0 (S = 4.989e+13). This means that the observed correlation is unlikely to be due to random chance. We reject H0 and accept H3.</p>
<p><em>In practice, the analysis suggests that the shorter the distance shot in a basketball game, there is a tendency for the efficiency rate to increase, although the relationship is weak.</em></p>
<blockquote class="blockquote">
<p>Note: Considering the main hypothesis and the correlation coefficient obtained in minutes remaining, seconds remaining and distance shot, we can conclude that although all variables are related to the Efficiency Rate, the distance shot has a higher correlation on the efficiency rate than the other two time conditionals. In the share phase, we will focus the interactive visualization in distance shots and efficiency rate as it’s an important variable that the main coach want to analyze.</p>
</blockquote>
<blockquote class="blockquote">
<p>This information can be valuable for basketball teams and coaches in understanding the dynamics of the game and making strategic decisions based on the remaining time/location variables of the shot and the efficiency rate.</p>
</blockquote>
<p><br>
</p>
</section>
</section>
<section id="share-phase" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Share Phase</h1>
<hr style="border: 1px solid black;">
<section id="interactive-dashboard-distance-shot-and-efficiency-rate-by-year-2015-2023" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="interactive-dashboard-distance-shot-and-efficiency-rate-by-year-2015-2023"><span class="header-section-number">5.1</span> Interactive Dashboard: Distance shot and efficiency rate by year (2015-2023)</h2>
<p>The main coach wants to see the changes throughout the years for further analysis. An Interactive Dashboard was crafted to show the distribution of distance shot and efficiency rate from 2015 to 2023.</p>
<p><a href="https://ablasettikuhn.shinyapps.io/dashboard-app/"> <img src="Dashboard_Screenshot.PNG" alt="Shiny App" style="width: 100%;"> </a></p>
<blockquote class="blockquote">
<p>Access the interactive visualization over the years by clicking on the image above or <a href="https://ablasettikuhn.shinyapps.io/dashboard-app/"><strong>CLICK HERE</strong></a> to access the Interactive Dashboard created with Shiny and hosted on Shinyapps.io.</p>
</blockquote>
<!--#First we need to define the UI for the dashboard:

ui <- dashboardPage(
  skin = "black",  # Use a neutral color theme for the header
  
  dashboardHeader(title = tags$strong("Interactive Dashboard"),
                  titleWidth = 258),  # Title remains unchanged
  
  dashboardSidebar(
    width = 300,
    sliderInput("year", "Select Year", 
                min = min(nba_nuggets_shots$yearSeason),
                max = max(nba_nuggets_shots$yearSeason),
                value = min(nba_nuggets_shots$yearSeason),
                step = 1),
    h4("Boxplot interpretation", style = "padding: 10px;"),
    # Apply padding directly in the p tag for both the description title and content
    p("The boxes represent the interquartile range (25% to 75% of the observations), 
       filled in green for shots made and red for shots missed. 
       The vertical line inside the box represents the median (50% of the observations). 
       The black diamond represents the mean, and black points represent outliers.",
      style = "padding: 10px; text-align: justify;"),  # Added padding for better readability
    h4("Insights", style = "padding: 10px;"),
    # Apply padding directly in the p tag for both the description title and content
    p("75% of shots made increased from 19 feet in 2015 to 23 feet in 2023. 
      There is a higher frequency of successful longer-range shots, aligning with the NBA's trend toward three-point shooting over the years. 
      50% of shots made decreased slightly from 5 feet in 2015 to 4 feet in 2023. 
      Despite the overall increase in three-pointers, the efficiency of attempts near the basket remained important.
      This reflects modern NBA offensive strategies, where teams seek to maximize efficiency by focusing on three-pointers and close-range finishes.",
      style = "padding: 10px; text-align: justify;")
  ),
  
  dashboardBody(
    fluidRow(
      box(
        title = tags$strong("Distribution of Distance Shot by Efficiency Rate"), 
        solidHeader = TRUE, 
        width = 12,
        plotOutput("plot")
      )
    ),
    fluidRow(
      box(
        title = tags$strong("Summary Statistics"), 
        solidHeader = TRUE, 
        width = 12,
        tableOutput("summary_table")
      )
    )
  )
)

#Second we need to define the server logic and third run the shinyApp: `shinyApp(ui, server)`. By defining `runtime: shiny` in the YAML, the dashboard is displayed in the html document.

server <- function(input, output) {
  
  # Reactive plot based on year selection
  output$plot <- renderPlot({
    filtered_data <- nba_nuggets_shots %>%
      filter(yearSeason == input$year)  # Filter data for selected year
    
    ggplot(filtered_data, aes(x = distanceShot, y = isShotMade, fill = isShotMade)) +
      geom_boxplot() + 
      stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "black", 
                   position = position_dodge(width = 0.75)) +
      scale_fill_manual(values = c("#F8766D", "lightgreen")) +
      labs(x = "Distance Shot", y = "Is Shot Made", fill = "Is Shot Made?") +
      facet_wrap(~yearSeason, ncol = 3, scales = "fixed") +
      scale_x_continuous(limits = c(0, 85)) + 
      theme_minimal()
  })
  
  # Generate the summary statistics for the table
  output$summary_table <- renderTable({
    filtered_data <- nba_nuggets_shots %>%
      filter(yearSeason == input$year)  # Filter data for selected year
    
    # Calculate boxplot components
    summary_stats <- filtered_data %>%
      mutate(isShotMade = factor(isShotMade, levels = c(TRUE, FALSE))) %>%  # Reorder levels
      group_by(isShotMade) %>%
      summarise(
        Min = min(distanceShot, na.rm = TRUE),
        Q1 = quantile(distanceShot, 0.25, na.rm = TRUE),
        Median = median(distanceShot, na.rm = TRUE),
        Mean = mean(distanceShot, na.rm = TRUE),
        Q3 = quantile(distanceShot, 0.75, na.rm = TRUE),
        Max = max(distanceShot, na.rm = TRUE)
      )
    
    summary_stats  # Display the summary statistics
  })
}

# Run the application and use rsconnect::deployApp('path-to-your-app')

shinyApp(ui = ui, server = server)-->
<p><br>
</p>
</section>
<section id="distribution-of-distance-shot-by-efficiency-rate" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="distribution-of-distance-shot-by-efficiency-rate"><span class="header-section-number">5.2</span> Distribution of Distance Shot by Efficiency Rate</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nba_nuggets_shots, <span class="fu">aes</span>(<span class="at">x =</span> distanceShot, <span class="at">y =</span> isShotMade, <span class="at">fill =</span> isShotMade)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">shape =</span> <span class="dv">23</span>, <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">fill =</span> <span class="st">"black"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.75</span>)) <span class="sc">+</span> <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#F8766D"</span>, <span class="st">"lightgreen"</span>)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Distance Shot"</span>, <span class="at">y =</span> <span class="st">"Is Shot Made"</span>, <span class="at">fill =</span> <span class="st">"Is Shot Made?"</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Distribution of Distance Shot by Efficiency Rate"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Google_DA_Capstone_Project_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>The boxplot above shows the distribution of shot distances based on the efficiency rate. The boxes represent the interquartile range (0.25 to 0.75 percent of the observations), filled in green for shots made and red for shots missed. The vertical line inside the box represents the median (0.50 of the observations). The black diamond represents the mean. The mean for shots missed is below the median and the mean for shots converted is above the median. The means are relatively similar, but the median for shots missed is higher than the median for shots converted, indicating that shots converted tend to be in shorter distances, while shots missed tend to be in longer distances. The black points represent outliers, with more shots missed in long distances, this means few shots converted in super long distances.</p>
</blockquote>
<p><br>
</p>
</section>
<section id="distribution-of-minutes-left-by-efficiency-rate" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="distribution-of-minutes-left-by-efficiency-rate"><span class="header-section-number">5.3</span> Distribution of Minutes Left by Efficiency Rate</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nba_nuggets_shots, <span class="fu">aes</span>(<span class="at">x =</span> minutesRemaining, <span class="at">fill =</span> isShotMade)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"count"</span>) <span class="sc">+</span> <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#F8766D"</span>, <span class="st">"lightgreen"</span>)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Minutes Remaining"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">fill =</span> <span class="st">"Is Shot Made?"</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Distribution of Minutes Left by Efficiency Rate"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Google_DA_Capstone_Project_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>The barplot above shows the distribution of minutes remaining based on the efficiency rate. The bars represent the count of shots converted in green and shots missed in red, based on the minutes left. The first tall bar shows a higher number of shots missed when there is 1 minute left. The last two bars show a smaller number of shots missed when there are 11 minutes left, and no shots when the game quarter starts (12 minutes left).</p>
</blockquote>
<p><br>
</p>
</section>
<section id="distribution-of-seconds-left-by-efficiency-rate" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="distribution-of-seconds-left-by-efficiency-rate"><span class="header-section-number">5.4</span> Distribution of Seconds Left by Efficiency Rate</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nba_nuggets_shots, <span class="fu">aes</span>(<span class="at">x =</span> secondsRemaining, <span class="at">fill =</span> isShotMade)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"count"</span>) <span class="sc">+</span> <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#F8766D"</span>, <span class="st">"lightgreen"</span>)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Seconds Remaining"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">fill =</span> <span class="st">"Is Shot Made?"</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Distribution of Seconds Left by Efficiency Rate"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Google_DA_Capstone_Project_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>The barplot above shows the distribution of seconds remaining based on the efficiency rate. The bars represent the count of shots converted in green and shots missed in red, based on the seconds left. The first tall bar shows a higher number of shots missed when there are between 1 and 1.5 seconds left. Also, the shots made are higher when there are between 1 and 1.5 seconds left. The last bar shows there are no shots when the game countdown clock starts (60 seconds left).</p>
</blockquote>
<p><br>
</p>
</section>
</section>
<section id="act-phase" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Act Phase</h1>
<hr style="border: 1px solid black;">
<section id="summary" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">6.1</span> Summary</h2>
<p><strong>Conclusion</strong></p>
<ul>
<li><p>The business task was performed and analyzed based on the problem that the main coach wanted to understand. The relation between minutes left, seconds left, distance shot and Efficiency Rate was successful measured and analyzed.</p></li>
<li><p>The main hypothesis was confirmed, there is a relationship between minutes left, seconds left, distance shot and the efficiency rate. Although all variables are related to the Efficiency Rate, the distance shot has a higher relationship with the efficiency rate than the other two time conditionals.</p></li>
<li><p>Understanding the constraints of the game is a powerful decision-making strategy. Shots effectuated from a smaller distance to the hoop tend to be more effective, this applies to all years. If the coach wants to control more the unexpected conditionals during the game, shorter distance shots with fewer seconds left in the countdown clock is a good strategy. The relationship between minutes remaining is more stable throughout the game, that’s why no matter in which quarter of the game, the strategy of shooting close to the rim and close to zero in the countdown clock is a way to clear out unexpected conditionals.</p></li>
<li><p>This information can be valuable for all NBA basketball teams and coaches as it can lead to further research. In this particular case study the time/location variables of the shot were analyzed and related to the efficiency rate only.</p></li>
</ul>
<p><strong>Long-distance shots trend in NBA: What’s all the controversy about?</strong></p>
<p>Despite the rise in three-point attempts, efficiency near the basket remained crucial. This highlights modern NBA offensive strategies, where teams aim to maximize scoring efficiency by prioritizing both three-pointers and close-range finishes. Did the Denver Nuggets win the 2023 finals thanks to three-pointers? The insights show that a balanced approach proves to be the winning formula.</p>
<p><strong>Open inverstigation lines</strong></p>
<ul>
<li><p>Although there are exeptions, humans perform better under pressure, and high performance athletes are used to work under pressure. The positioning of opposing players in a short distance to the hoop plus the countdown clock could play a role in the efficiency rate. In this study we focus on controllable time/location conditionals, we do not know what effect an opposing player might have had on these results.</p></li>
<li><p>The period of time taken was from 2015 to 2023 but the purpose of the coach was not to analyze the years separately. This can be performed as part of a new business task if the main focus changes to identify the differences between 2015 to 2023 seasons.</p></li>
<li><p>In the share phase, the visualizations were focused on distance shots as it’s an important variable that the main coach can control and train. Dashboards for minutes and seconds remaining can be included as part of a redefinition of the business task.</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>