name: Render Rmd to HTML

on:
  push:
    branches:
      - main # Replace with your default branch

jobs:
  render:
    runs-on: ubuntu-latest

    container:
      image: rocker/r-ver:4.1.3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        R -e "install.packages(c('rmarkdown', 'shiny', 'ISAR', 'tidyverse', 'skimr'))"

    - name: Render Rmd
      run: |
        R -e "rmarkdown::render('Google DA Case Study.Rmd')"
