name: Render Rmd to HTML

on:
  push:
    branches:
      - main # Replace with your default branch

jobs:
  render:
    runs-on: windows-latest # Use the Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.3.1

    - name: Install Pandoc # Add this step to install Pandoc
      run: |
        # You don't need sudo on Windows
        choco install pandoc

    - name: Install dependencies
      run: R -e "install.packages(c("rmarkdown", "shiny", "ISAR", "tidyverse", "skimr"))"

    - name: Render Rmd
      run: R -e 'rmarkdown::render("Google_DA_Capstone_Project.Rmd")'
