name: Render Rmd to HTML

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.3.1

    - name: Install Pandoc
      run: choco install pandoc

    - name: Install dependencies
      run: "C:\\Program Files\\R\\R-4.3.1\\bin\\x64\\R" -e "install.packages(c('rmarkdown', 'shiny', 'ISAR', 'tidyverse', 'skimr'))"

    - name: Render Rmd
      run: "C:\\Program Files\\R\\R-4.3.1\\bin\\x64\\Rscript" -e 'rmarkdown::render("Google_DA_Capstone_Project.Rmd")'

    - name: Move HTML file to root directory
      run: mv Google_DA_Capstone_Project.html .

    - name: Commit and push rendered HTML
      run: |
        git config user.name "ablasettikuhn"
        git config user.email "alex_blasetti@hotmail.com"
        git add Google_DA_Capstone_Project.html
        git commit -m "Render and publish HTML file"
        git push
