name: Render Rmd to HTML

on:
  push:
    branches:
      - main # Replace with your default branch

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '16'

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.1.0

    - name: Install Pandoc # Add this step to install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Install dependencies
      run: R -e 'install.packages(c("rmarkdown", "knitr", "shiny", "ISAR", "tidyverse", "skimr"))'

    - name: Render Rmd
      run: R -e 'rmarkdown::render("Google DA Case Study.Rmd")'
