name: Render Rmd to HTML

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: virtual-lab/setup-r@v1
      with:
        r-version: 4.1.0

    - name: Install Pandoc
      run: choco install pandoc

    - name: Install dependencies
      run: R -e "install.packages(c('rmarkdown', 'shiny', 'ISAR', 'tidyverse', 'skimr'))"

    - name: Render Rmd
      run: R -e "rmarkdown::render('Google_DA_Capstone_Project.Rmd')"

    - name: Move HTML file to root directory
      run: mv Google_DA_Capstone_Project.html .

    - name: Commit and push rendered HTML
      run: |
        git config user.name "ablasettikuhn"
        git config user.email "alex_blasetti@hotmail.com"
        git add Google_DA_Capstone_Project.html
        git commit -m "Render and publish HTML file"
        git push
